# fly.toml app configuration file generated for sphericalk-at on 2025-04-08T14:24:08+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sphericalk-at'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
